#!/bin/sh
# Run by Strap after installing Brewfile dependencies

cd $(dirname $0)/..

script/extract-onepassword-secrets
script/install-vscode-extensions
script/install-oh-my-zsh
script/install-valet

if [ "$SHELL" != "/bin/zsh" ]
then
  chsh -s /bin/zsh neds
fi
